version: '3.7'
services:
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - ./db:/data
        restart: always
    app:
        container_name: flaskapp
        image: ke2ek/flaskapp:1.0
        command: python app.py
        ports:
            - "80:80"
        volumes:
            - ./pyflask:/code
        depends_on:
            - redis
